// LOGIN PAGE
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOGIN_HANDLE_CHANGE = "LOGIN_HANDLE_CHANGE";
export const PASSWORD_HANDLE_CHANGE = "PASSWORD_HANDLE_CHANGE";
export const LOGIN_SUBMIT = "LOGIN_SUBMIT";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_RECEIVE = "AUTH_RECEIVE";
export const AUTH_ERROR = "AUTH_ERROR";

// ORGANIZATION PAGE
export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
export const CHANGE_ORGANIZATION = "CHANGE_ORGANIZATION";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_INPUT_MODAL = "OPEN_INPUT_MODAL";
export const CLOSE_INPUT_MODAL = "CLOSE_INPUT_MODAL";
export const SET_EDITED_ORGANIZATION = "SET_EDITED_ORGANIZATION";
export const CHANGE_MODAL_INPUT_ORGANIZATION = "CHANGE_MODAL_INPUT_ORGANIZATION";
export const CHANGE_TO_FALSE_MODAL_INPUT_ORGANIZATION = "CHANGE_TO_FALSE_MODAL_INPUT_ORGANIZATION";
export const REQUEST_ORGANIZATIONS = "REQUEST_ORGANIZATIONS";
export const RECEIVE_ORGANIZATIONS = "RECEIVE_ORGANIZATIONS";
export const ORGANIZATION_TITLE_HANDLE_CHANGE = "ORGANIZATION_TITLE_HANDLE_CHANGE";
export const ORGANIZATION_ID_HANDLE_CHANGE = "ORGANIZATION_ID_HANDLE_CHANGE";
export const ORGANIZATION_ADDRESS_HANDLE_CHANGE = "ORGANIZATION_ADDRESS_HANDLE_CHANGE";
export const ORGANIZATION_INN_HANDLE_CHANGE = "ORGANIZATION_INN_HANDLE_CHANGE";

